- name: Подготавилваю файловую систему
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'
  with_items:
    - "{{ deploy_path }}"
    - "{{ deploy_path }}/www"

- name: Выкатываю релиз
  synchronize:
    src: "{{ deploy_src }}/"
    dest: "{{ deploy_path }}/www"
    use_ssh_args: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"

- name: Удаляю ненужные директории
  file:
    state: absent
    path: "{{ deploy_path }}/www/{{ item }}"
  with_items: "{{ remove_dirs }}"
    
- name: Устанавливаю права доступа
  file:
    path: "{{ deploy_path }}/www"
    state: directory
    owner: apache
    group: apache
    recurse: yes

- name: Подключаю внешние папки
  file:
    src: "{{ external_data_path }}/{{ item.src }}"
    dest: "{{ deploy_path }}/www/{{ item.dest }}"
    state: link
    owner: apache
    group: apache
    force: yes
  with_items: "{{ external_data }}"


- name: Выкладываю .env файл из {{ envfile_src }}
  copy:
    src: "{{ envfile_src }}"
    dest: "{{ deploy_path }}/.env"
    mode: "0644"
    owner: apache
    group: apache


- name: Дополняю envfile
  lineinfile:
    path: "{{ deploy_path }}/.env"
    line: "{{ item }}"
    insertafter: EOF
  with_file: 
    - "{{ envfile_common }}"

