- name: install nginx
  yum:
    name:
      - "nginx"
    state: present

- name: Enable nginx
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Enabled firewall
  ansible.posix.firewalld:
    zone: public
    permanent: yes
    service: http
    state: enabled
    immediate: yes