- name: Включаю .env
  file:
    src: "{{app_basepath}}/{{app_release_name}}.env"
    dest: "{{app_basepath}}/.env"
    state: link
    owner: apache
    group: apache
    force: yes

- name: Включаю новый релиз
  file:
    src: "{{app_path}}"
    dest: "{{app_current_release_path}}"
    state: link
    owner: apache
    group: apache

- name: Сбрасываю OpCache
  import_tasks: tasks/webserver/php-resetopcache.yml

- stat:
   path: "{{ app_basepath }}/{{ app_release_name }}.crontab"
  register: cronfile_stat

- debug:
    msg: "{{ crontab_source }} найден, делаем симлинк"

- name: Делаю симлинк кронтаба
  when: cronfile_stat.stat.exists == True and cronfile_stat.stat.islnk == False
  file:
    src: "{{ app_basepath }}/{{ app_release_name }}.crontab"
    dest: "{{custom_crontab_files}}/apache"
    state: link
    owner: apache
    group: apache

- debug:
    msg: "{{ crontab_source }} не найден"
  when: cronfile_stat.stat.exists == False