
- name: Включаю новый релиз
  file:
    src: "{{app_path}}"
    dest: "{{app_current_release_path}}"
    state: link
    owner: apache
    group: apache

- name: Сбрасываю OpCache
  import_tasks: tasks/webserver/php-resetopcache.yml
  when: php_v == '7.2'

- name: Сбрасываю OpCache
  import_tasks: tasks/webserver/php-resetopcache.yml
  when: php_v == '7.4'

- name: Сбрасываю OpCache
  import_tasks: tasks/webserver/php-resetopcache.yml
  when: php_v == '8.0'

- stat:
   path: "{{ app_basepath }}/{{ app_release_name }}.crontab"
  register: cronfile_stat

- debug:
    msg: "{{ crontab_source }} найден, делаем симлинк"

