- name: Подготавилваю файловую систему
  file:
    path: "{{app_path}}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Получаю приложение из репозитория
  git:
    repo: "{{app_git_repo}}"
    dest: "{{app_path}}"
    version: "{{app_release_commit}}"
    force: yes

- name: Удаляю ненужные директории
  file:
    state: absent
    path: "{{app_path}}/{{item}}"
  with_items:
    - upload
    - docker

- name: Подключаю внешние папки
  file:
    src: "{{app_data_path}}/{{item.src}}"
    dest: "{{app_path}}/{{item.dest}}"
    state: link
    owner: nginx
    group: nginx
    force: yes
  with_items:
    - src: download
      dest: download
    - src: exchange
      dest: exchange
    - src: exchange_archive
      dest: exchange_archive
    - src: pays
      dest: pays
    - src: users
      dest: cleversite/user
    - src: ipts
      dest: callback/wav
    - src: upload
      dest: upload

- name: Выкладываю .env файл ({{envfile}})
  copy:
    dest: "{{app_basepath}}/.env"
    src: "{{envfile}}"

- debug:
    msg: "Deploy to {{app_domain}}"

- name: Обновляю конфиг NGINX
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/web.cleversite.conf

- name: Перезагружаю nginx
  shell: "{{item}}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"

- stat:
    path: "{{app_current_release_path}}"
  register: current_stat

- debug:
    msg: "{{current_stat}}"

- name: Делаю бэкап текущего релиза
  when: current_stat.stat.exists == True and current_stat.stat.lnk_target != app_path
  shell: "cp -P {{app_current_release_path}} {{app_backup_release_path}}"


- name: Выключаю новый релиз
  file:
    src: "{{app_path}}"
    dest: "{{app_current_release_path}}"
    state: link
    owner: nginx
    group: nginx