- name: Создаю папки для логов NGINX
  file:
    path: /var/log/nginx/cleversite
    state: directory
    mode: "0777"

- name: Обновляю конфиг NGINX
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/web.cleversite.conf

- name: Перезагружаю nginx
  shell: "{{item}}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"