- name: Prepare filesystem
  file:
    path: "{{app_path}}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Get application from git
  git:
    repo: "{{app_git_repo}}"
    dest: "{{app_path}}"
    version: "{{app_release_commit}}"


- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/web.cleversite.conf

- name: Test and reload nginx
  shell: "{{item}}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"

- stat:
    path: "{{app_current_release_path}}"
  register: current_stat

- debug:
    msg: "{{current_stat}}"

- name: Backup current release
  when: current_stat.stat.lnk_target == app_path
  shell: "cp -P {{app_current_release_path}} {{app_backup_release_path}}"


- name: Switch app release
  file:
    src: "{{app_path}}"
    dest: "{{app_current_release_path}}"
    state: link
    owner: nginx
    group: nginx