- stat:
    path: "{{app_current_release_path}}"
  register: current_release_stat

- debug: 
    msg: "{{current_release_stat}}"
    
- name: Делаю бэкап активного релиза
  when: current_release_stat.stat.exists == True and current_release_stat.stat.islnk == True
  file:
    src: "{{current_release_stat.stat.lnk_target}}"
    dest: "{{app_backup_release_path}}"
    state: link
    owner: apache
    group: apache
    force: yes

- stat:
    path: "{{app_current_env_path}}"
  register: current_env_stat

- debug: 
    msg: "{{current_env_stat}}"
    
- name: Делаю бэкап env активного релиза
  when: current_env_stat.stat.exists == True and current_env_stat.stat.islnk == True
  file:
    src: "{{current_env_stat.stat.lnk_target}}"
    dest: "{{app_backup_release_path}}.env"
    state: link
    owner: apache
    group: apache
    force: yes

- name: Делаю бэкап env активного релиза. Копирую файл
  when: current_env_stat.stat.exists == True and current_env_stat.stat.isreg == True
  file:
    src: "{{current_env_stat.stat.lnk_target}}"
    dest: "{{app_backup_release_path}}.file.env"
    state: present
    owner: apache
    group: apache
    force: yes

- name: Делаю бэкап env активного релиза. Копирую файл
  when: current_env_stat.stat.exists == True and current_env_stat.stat.isreg == True
  file:
    src: "{{app_backup_release_path}}.file.env"
    dest: "{{app_backup_release_path}}.env"
    state: link
    owner: apache
    group: apache
    force: yes

- stat:
   path: "{{ custom_crontab_files }}/apache"
  register: current_cron_stat

- debug:
    msg: "{{current_cron_stat}}"

- name: Делаю бэкап активного кронтаба если он симлинк
  when: current_cron_stat.stat.exists == True and current_cron_stat.stat.islnk == True
  file:
    src: "{{ current_cron_stat.stat.lnk_target }}"
    dest: "{{ app_basepath }}/backup.crontab"
    state: link
    owner: apache
    group: apache
    force: yes

- name: Делаю бэкап активного кронтаба если файл регулярный
  when: current_cron_stat.stat.exists == True and current_cron_stat.stat.isreg == True
  copy:
    src: "{{ custom_crontab_files }}/apache"
    dest: "{{ app_basepath }}/backup.crontab"
    remote_src: True
    owner: apache
    group: apache
