- name: Чтение из {{crontab_source}}
  command: cat "{{ app_path }}/{{crontab_source}}"
  register: crontab_content

- name: Создание .crontab
  cron:
    cron_file: "{{app_basepath}}/{{app_release_name}}.crontab"
    job: php {{app_current_release_path}}/{{item.script}} >> {{item.log}}
    name: "{{ item.description }}"
    minute: "{{s item.minute }}"
    hour: "{{ item.hour | default('*')}}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
    state: present
    user: apache
    with_items: "{{ crontab_content.stdout | from_yaml }}"

- name: Изменение прав доступа
  file:
    path: "{{app_basepath}}/{{app_release_name}}.crontab"
    state: file
    mode: 0660
    owner: apache
    group: apache
