- name: Включаю новый релиз
  file:
    src: "{{ release_path }}"
    dest: "{{ current_release_path }}"
    state: link
    owner: apache
    group: apache


- name: Сбрасываю OpCache
  import_tasks: tasks/webserver/php-resetopcache.yml
