- name: Проверяю текущий релиз
  stat:
    path: "{{ current_release_path }}"
  register: current_release_stat

- debug: 
    msg: "{{ current_release_stat }}"

- name: Делаю бэкап активного релиза
  when: current_release_stat.stat.exists == True and current_release_stat.stat.islnk == True
  file:
    src: "{{ current_release_stat.stat.lnk_target }}"
    dest: "{{ backup_release_path }}"
    state: link
    owner: apache
    group: apache
    force: yes
