- name: Подготавилваю файловую систему
  file:
    path: "{{app_path}}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Выкатываю релиз
  synchronize:
    src: "{{app_src}}/"
    dest: "{{app_path}}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"

- name: Вычищаю cleversite/vendor
  file:
    path: "{{app_path}}/cleversite/vendor"
    state: absent

- name: Устанавливаю зависимости
  shell: composer install -n 
  args:
    chdir: "{{app_path}}/cleversite"

- name: Удаляю ненужные директории
  file:
    state: absent
    path: "{{app_path}}/{{item}}"
  with_items:
    - upload
    - docker
    - .git

- name: Устанавливаю права доступа
  file:
    path: "{{app_path}}"
    state: directory
    owner: apache
    group: apache
    recurse: yes

- name: Проверяю внешние папки
  file:
    path: "{{item.src}}"
    state: directory
    mode: "0775"
    owner: apache
    group: apache
    force: yes
  with_items: "{{app_external_data}}"    

- name: Подключаю внешние папки
  file:
    src: "{{item.src}}"
    dest: "{{app_path}}/{{item.dest}}"
    state: link
    owner: apache
    group: apache
    force: yes
  with_items: "{{app_external_data}}"



- name: Выкладываю .env файл из {{envfile_local}}
  copy:
    dest: "{{app_basepath}}/{{app_release_name}}.env"
    src: "{{envfile_local}}"    


- name: Дополняю envfile
  lineinfile:
    path: "{{app_basepath}}/{{app_release_name}}.env"
    line: "{{item}}"
    insertafter: EOF
  with_file: 
    - "{{envfile_common}}"



