
# Выкатываем релиз
- import_tasks: deploy-app.yaml
  when: task == "deploy"
# Делаем бэкап
- import_tasks: make-backup.yaml
  when: task == "deploy"
# Активируем релиз
- import_tasks: activate-release.yaml
  when: task == "deploy"



- import_tasks: rollback-app.yaml
  when: task == "rollback"
