- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/mobile.cleversite.conf

- name: Test and reload nginx
  shell: "{{item}}"
  with_items:
    - "nginx -t"
    - "nginx -s reload"

