- name: Prepare fs
  file:
    path: "{{app_path}}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Get application from git
  git:
    repo: "{{app_git_repo}}"
    dest: "{{app_path}}"
    version: "{{app_release_commit}}"
    force: yes



- stat:
    path: "{{app_current_release_path}}"
  register: current_stat

- stat:
    path: "{{app_backup_release_path}}"
  register: backup_stat

- debug:
    msg: "{{current_stat}}"
- debug:
    msg: "{{backup_stat}}"

- name: Backup current release
  when: current_stat.stat.exists == True and current_stat.stat.lnk_target != app_path
  shell: "cp -P {{app_current_release_path}} {{app_backup_release_path}}"

- import_tasks: deploy-nginx.yaml

- name: Switch app release
  file:
    src: "{{app_path}}"
    dest: "{{app_current_release_path}}"
    state: link
    owner: nginx
    group: nginx