- name: Prepare fs
  file:
    path: "{{ app_path }}"
    state: directory
    mode: "0777"
    owner: apache
    group: apache

- name: Get application from git
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ app_path }}"
    version: "{{ app_release_commit }}"
    force: yes

- name: Конфигурирование npm репозитория  
  shell: npm set registry http://npm.servicecloud.info:8080
  become_user: apache

- name: Install modules
  shell: npm install
  args:
    chdir: "{{ app_path }}"
    creates: "{{ app_path }}/node_modules"
  become_user: apache

- name: add envfile
  copy:
    src: "{{ envfile }}"
    dest: "{{ app_path }}/.env"
    mode: "0644"
    owner: apache
    group: apache

- name: Link envfile
  file:
    src: "{{ app_path }}/.env"
    dest: "{{ envfile }}"
    state: "link"    
    mode: "0644"
    owner: apache
    group: apache

- name: Link logs directory
  file:
    src: "/var/log/cleversite/ws"
    dest: "{{ app_path }}/log"
    state: "link"
    mode: "0775"
    owner: apache
    group: apache

- name: Read current release_path
  stat:
    path: "{{ app_current_release_path }}"
  register: current_stat



- name: Backup current release
  when: current_stat.stat.exists == True and current_stat.stat.lnk_target != app_path
  shell: "cp -P {{ app_current_release_path }} {{ app_backup_release_path }}"


- name: Switch current release
  file:
    src: "{{ app_path }}"
    dest: "{{ app_current_release_path }}"
    state: link
    owner: apache
    group: apache

- name: Install systemd services
  import_tasks: install-systemd-service.yaml

#- name: Install nginx configs
#  import_tasks: nginx.yaml
